#!/bin/sh

# set variables
. /etc/sysconfig/eos
XRD_COREDIR="/var/spool/eos/core"
EOS_MQ_MASTER_FILE="/var/eos/eos.mq.master"
EOS_SET_MASTER="${EOS_SET_MASTER:-0}"
PATH=$PATH:/sbin

source /entrypoints/include/disable-ipv6.sh
source /entrypoints/include/setup-keytab.sh
sed -i '0,/eos.keytab/{s/eos.keytab/eos.client.keytab/}' /etc/xrd.cf.mq

chown -R daemon:daemon /var/log/eos/
chown -R daemon:daemon /var/eos/

# check if this node is a master - if so, create the relevant file
if [ "z${EOS_SET_MASTER}" = "ztrue" ] || [ "${EOS_SET_MASTER}" -eq 1 ]; then
    touch "${EOS_MQ_MASTER_FILE}"
fi

# remove potential duplicate lines from mq config
sed -i '/mqofs.qdbcluster/d' /etc/xrd.cf.mq
sed -i '/mqofs.qdbpassword_file/d' /etc/xrd.cf.mq

# check if we should use quarkdb, if so set correct config
if [ "${EOS_USE_QDB}" = "true" ] || [ "${EOS_USE_QDB}" = 1 ]; then
  echo "mqofs.qdbcluster ${EOS_QDB_NODES}" >> /etc/xrd.cf.mq
  echo "mqofs.qdbpassword_file /etc/eos.client.keytab" >> /etc/xrd.cf.mq
fi

# start mq
mkdir -p ${XRD_COREDIR} && chown daemon:daemon ${XRD_COREDIR}
echo "Starting mq for " $(rpm -q eos-server | sed s/eos-server-//g)
cd ${XRD_COREDIR}

XRDPROG=/usr/bin/xrootd
test -e /opt/eos/xrootd/bin/xrootd && XRDPROG=/opt/eos/xrootd/bin/xrootd

exec $XRDPROG -n mq -c /etc/xrd.cf.mq -l /var/log/eos/xrdlog.mq -Rdaemon
